alias python='python3.13'
alias aseprite='/home/kevinsilberberg/repos/aseprite/build/bin/aseprite'
alias pluto='julia /home/kevinsilberberg/.runPluto.jl'
alias emacs='/home/kevinsilberberg/repos/emacs/src/emacs'
alias lock='xdg-screensaver lock'
alias cl='clear'
alias ga='git add'
alias gc='git commit -m'